# Generated by Django 2.1.2 on 2018-11-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Cash', 'Cash'), ('Eqity', 'Eqity'), ('KCB', 'KCB'), ('National', 'National')], default='', max_length=80),
        ),
    ]
