# Generated by Django 2.1.2 on 2018-11-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
