# Generated by Django 2.1.2 on 2018-11-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finplanner', '0002_auto_20181101_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank',
            field=models.CharField(choices=[('Standard Chartered', 'Standard Chartered'), ('KCB', 'KCB'), ('Equity', 'EQUITY')], default='', max_length=100),
        ),
    ]
