# Generated by Django 2.1.2 on 2018-11-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finplanner', '0003_auto_20181108_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
    ]
