# Generated by Django 2.1.2 on 2018-11-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finplanner', '0003_profile_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
