# Generated by Django 2.1.2 on 2018-11-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finplanner', '0004_auto_20181105_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bank',
        ),
    ]
