# Generated by Django 2.1.2 on 2018-11-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finplanner', '0005_remove_profile_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.CharField(default='', max_length=100),
        ),
    ]
